### ISSUE TITLE
Pagination on blog does not work

### ISSUE THREAD

**Issue by rbhensley** [sitecrafting/groot#35]
list of articles stays the same when navigating to other pages, going back to using Timber::get_posts() instead of conifers BlogPost::get_all() resolved the issue

Projects that had this problem were TRA and WWVWA

**Comment by acobster** [comment]
Moved to Conifer.

**Comment by acobster** [comment]
@rbhensley it turns out that because this has implications for other parameters, like `category__in`, the best place to fix this _is_ in the default Blog archive code in the starter theme, where we're actually calling `BlogPost::get_all()`. For other use-cases, we'll likely have to tweak the parameters we pass in, e.g. not every post type is going to support the `category` taxonomy. So I added default filters for category and page in `index.php`, and we'll just need to make sure when we're supporting pagination on custom post types going forward that we include the appropriate params for those.

I added some clarifying notes to the Conifer docs about this as well. Thanks!
